In [5]:
import pandas as pd
df = pd.read_excel('/content/Student new.xlsx')

In [6]:
df

       Name  Roll_No  Age
0  Karishma        1   19
1     Pooja        2   18
2      Riya        3   20
3    Sanjay        4   18

In [7]:
df.insert(3,"Gender",["Female","Female","Female","Male"])
print(df)

       Name  Roll_No  Age  Gender
0  Karishma        1   19  Female
1     Pooja        2   18  Female
2      Riya        3   20  Female
3    Sanjay        4   18    Male

In [10]:
df.loc[len(df)] = ["Immanuel", 6 , 20,"Male"]
print(df)

       Name  Roll_No  Age  Gender
0  Karishma        1   19  Female
1     Pooja        2   18  Female
2    Roshan        5   20    Male
3    Sanjay        4   18    Male
4    Roshan        5   20    Male
5  Immanuel        6   20    Male

In [16]:
df.drop('Age', axis = 1)

       Name  Roll_No  Gender
0  Karishma        1  Female
1     Pooja        2  Female
2    Roshan        5    Male
3    Sanjay        4    Male
4    Roshan        5    Male
5  Immanuel        6    Male

In [19]:
df.drop(df.index[2])

       Name  Roll_No  Age  Gender
0  Karishma        1   19  Female
1     Pooja        2   18  Female
3    Sanjay        4   18    Male
4    Roshan        5   20    Male
5  Immanuel        6   20    Male

In [20]:
print(df.replace(18,21))

       Name  Roll_No  Age  Gender
0  Karishma        1   19  Female
1     Pooja        2   21  Female
2    Roshan        5   20    Male
3    Sanjay        4   21    Male
4    Roshan        5   20    Male
5  Immanuel        6   20    Male

In [24]:
df["Name"] = df["Name"].str.lower()
print(df)

       Name  Roll_No  Age  Gender      Name
0  karishma        1   19  Female  karishma
1     pooja        2   18  Female     pooja
2    roshan        5   20    Male    roshan
3    sanjay        4   18    Male    sanjay
4    roshan        5   20    Male    roshan
5  immanuel        6   20    Male  immanuel